// ============================================================
// AUTO-GENERATED by build.js — DO NOT EDIT MANUALLY
// Generated: 2026-02-25T21:25:42.927Z
// ============================================================

const UNITS = {
    // --- Einstiegsdiagnose (LP1) ---
    "diagnose": {
        title: "Einstiegsdiagnose",
        description: "Teste dein Vorwissen zu Ableitungen. Das Ergebnis bestimmt deinen Lernpfad.",
        masteryThreshold: 0.8,
        tasks: [
            {
                id: "d1",
                question: "**Potenzregel**\n\nLeite die folgende Funktion ab:\n\n$$f(x) = 3x^4$$",
                answer: "12x^3",
                accepts: ["12x^3","12x³","12*x^3"],
                hints: ["Potenzregel: $f(x) = ax^n \\Rightarrow f'(x) = n \\cdot a \\cdot x^{n-1}$"],
                errorPatterns: {"3x^3":"Du hast den Vorfaktor vergessen! Bei $3x^4$ musst du $4 \\cdot 3 = 12$ rechnen.","12x^4":"Der Exponent muss um 1 kleiner werden: $n-1 = 3$."}
            },
            {
                id: "d2",
                question: "**Summenregel**\n\nLeite ab:\n\n$$f(x) = 5x^2 + 3x - 7$$",
                answer: "10x+3",
                accepts: ["10x+3","10x + 3","10*x+3","3+10x"],
                hints: ["Summenregel: Jeden Summanden einzeln ableiten. Konstanten fallen weg."],
                errorPatterns: {"10x+3-7":"Konstanten ($-7$) fallen beim Ableiten weg!","10x":"Die Ableitung von $3x$ ist $3$ — nicht vergessen!"}
            },
            {
                id: "d3",
                question: "**Wurzelfunktion**\n\nLeite ab:\n\n$$f(x) = \\sqrt{x}$$\n\nTipp: Schreibe die Wurzel zuerst als Potenz um.",
                answer: "1/(2*sqrt(x))",
                accepts: ["1/(2*sqrt(x))","1/(2√x)","0.5*x^(-0.5)","0,5*x^(-0,5)","1/2*x^(-1/2)","0.5x^(-0.5)"],
                hints: ["$\\sqrt{x} = x^{1/2}$ — jetzt Potenzregel anwenden!","$f(x) = x^{1/2} \\Rightarrow f'(x) = \\frac{1}{2} \\cdot x^{-1/2}$"],
                errorPatterns: {"1/2*x":"Fast! Aber der Exponent muss $\\frac{1}{2} - 1 = -\\frac{1}{2}$ sein."}
            },
            {
                id: "d4",
                question: "**Exponentialfunktion**\n\nLeite ab:\n\n$$f(x) = e^x$$",
                answer: "e^x",
                accepts: ["e^x","exp(x)","e^(x)"],
                hints: ["$e^x$ ist die einzige Funktion, die sich selbst als Ableitung hat."],
                errorPatterns: {"0":"$e^x$ ist keine Konstante!","x*e^(x-1)":"Vorsicht! Die Potenzregel gilt hier nicht. $e^x$ ist eine Exponentialfunktion, keine Potenz."}
            },
            {
                id: "d5",
                question: "**Negative Exponenten**\n\nLeite ab:\n\n$$f(x) = \\frac{1}{x^2}$$\n\nSchreibe den Bruch zuerst als $x^{-2}$ um.",
                answer: "-2/x^3",
                accepts: ["-2/x^3","-2x^(-3)","-2*x^(-3)","-2/x³"],
                hints: ["$\\frac{1}{x^2} = x^{-2}$ — jetzt Potenzregel!","$f'(x) = -2 \\cdot x^{-3} = \\frac{-2}{x^3}$"],
                errorPatterns: {"2/x^3":"Vorzeichen! $-2 \\cdot x^{-2-1} = -2x^{-3}$"}
            },
            {
                id: "d6",
                question: "**Regelwahl**\n\nWelche Ableitungsregel brauchst du für die Funktion\n$f(x) = x^2 \\cdot \\sin(x)$?",
                type: "choice",
                options: ["Potenzregel","Summenregel","Produktregel","Kettenregel"],
                correct: 2,
                hints: ["Zwei Funktionen werden multipliziert: $u(x) \\cdot v(x)$. Welche Regel gilt für Produkte?"],
            },
            {
                id: "d7",
                question: "**Regelwahl**\n\nWelche Ableitungsregel brauchst du für\n$f(x) = (3x+1)^5$?",
                type: "choice",
                options: ["Potenzregel","Summenregel","Produktregel","Kettenregel"],
                correct: 3,
                hints: [{"Eine Funktion ist in eine andere „eingesetzt":"äußere Funktion$($ innere Funktion$(x))$.\""}],
            },
            {
                id: "d8",
                question: "**Regelwahl**\n\nWelche Ableitungsregel brauchst du für\n$f(x) = e^{2x}$?",
                type: "choice",
                options: ["Potenzregel","Keine — $e^x$ bleibt $e^x$","Produktregel","Kettenregel"],
                correct: 3,
                hints: ["$e^{2x}$ ist nicht dasselbe wie $e^x$! Es steckt eine innere Funktion $2x$ drin."],
            },
        ]
    },

    // --- Steckbriefaufgaben (AS 6) ---
    "steckbrief": {
        title: "Steckbriefaufgaben",
        description: "Sie lernen, wie man aus gegebenen Eigenschaften (Punkte, Extrema, Steigungen)\ndie passende Funktionsgleichung rekonstruiert — eine Schlüsseltechnik\nfür technische Modellierungen.",
        explanation: "<h3>Vorgehen bei Steckbriefaufgaben</h3>\n<ol style=\"margin-left:1.5rem; line-height:2.2;\">\n  <li><strong>Funktionstyp wählen:</strong> Grad $n$ → $n+1$ Koeffizienten → Sie brauchen $n+1$ Bedingungen</li>\n  <li><strong>Bedingungen in Gleichungen übersetzen:</strong>\n    <ul>\n      <li>Punkt $(x_0 | y_0)$: Setze ein → $f(x_0) = y_0$</li>\n      <li>Extremum bei $x_0$: Die Steigung ist Null → $f'(x_0) = 0$</li>\n      <li>Wendepunkt bei $x_0$: Die Krümmung wechselt → $f''(x_0) = 0$</li>\n      <li>Steigung $m$ bei $x_0$: $f'(x_0) = m$</li>\n    </ul>\n  </li>\n  <li><strong>LGS aufstellen und lösen</strong> (Gauß-Verfahren oder CAS)</li>\n  <li><strong>Ergebnis prüfen:</strong> Setzen Sie die Lösung zurück in alle Bedingungen ein!</li>\n</ol>\n<div style=\"margin-top:1rem; padding:0.8rem; background:#fff3cd; border-radius:8px; color:#333;\">\n  <strong>Merke:</strong> Quadratische Funktion → 3 Koeffizienten → 3 Bedingungen.\n  Kubische Funktion → 4 Koeffizienten → 4 Bedingungen.\n</div>",
        masteryThreshold: 0.7,
        tasks: [
            {
                id: "sb1",
                question: "**Werkstückprofil — Bedingungen aufstellen**\n\nEin Werkstück hat ein Querschnittsprofil, das durch eine quadratische\nFunktion beschrieben wird:\n$$f(x) = ax^2 + bx + c$$\n\nAus der technischen Zeichnung liest Sie folgende Informationen ab:\n- Am linken Rand ($x = 0$) beträgt die Höhe $2\\,\\text{cm}$.\n- Am rechten Rand ($x = 4$) beträgt die Höhe $10\\,\\text{cm}$.\n- Am rechten Rand läuft das Profil waagerecht aus (horizontale Tangente).\n\n**Übersetze die erste Bedingung** „Höhe $2\\,\\text{cm}$ bei $x = 0$\" in eine\nGleichung für die Koeffizienten $a$, $b$, $c$.",
                answer: "c=2",
                accepts: ["c=2","c = 2","f(0)=2"],
                hints: ["Setze $x = 0$ in $f(x) = ax^2 + bx + c$ ein:\n$f(0) = a \\cdot 0^2 + b \\cdot 0 + c = c$.","Da $f(0) = 2$, folgt direkt: $c = 2$."],
                errorPatterns: {"2":"Richtig gedacht! Schreibe es als Gleichung: $c = 2$.","a=2":"Nicht $a$ — setze $x = 0$ ein: $f(0) = a \\cdot 0 + b \\cdot 0 + c = c$."}
            },
            {
                id: "sb2",
                question: "**Werkstückprofil — LGS lösen**\n\nAus dem Werkstückprofil $f(x) = ax^2 + bx + c$ mit den drei Bedingungen\nergibt sich das Gleichungssystem:\n\n$$\\begin{cases} c = 2 \\\\ 16a + 4b + c = 10 \\\\ 8a + b = 0 \\end{cases}$$\n\nDie erste Gleichung sagt Ihnen sofort: $c = 2$.\nDie dritte gibt Ihnen $b$ in Abhängigkeit von $a$: $b = -8a$.\n\n**Setzen Sie beides in die zweite Gleichung ein und berechne $a$, $b$ und $c$.**\nGib Ihr Ergebnis als `a; b; c` an.",
                answer: "-1/2; 4; 2",
                accepts: ["-1/2; 4; 2","-0.5; 4; 2","-0,5; 4; 2","a=-1/2, b=4, c=2","-0.5;4;2"],
                hints: ["Einsetzen: $16a + 4(-8a) + 2 = 10$.\nVereinfache: $16a - 32a = 8$, also $-16a = 8$.","$a = -\\frac{1}{2}$. Dann $b = -8 \\cdot (-\\frac{1}{2}) = 4$. Und $c = 2$."],
                errorPatterns: {"1/2; 4; 2":"Vorzeichen beachten! $-16a = 8$ ergibt $a = -\\frac{1}{2}$.","-1/2; -4; 2":"$b = -8a = -8 \\cdot (-\\frac{1}{2}) = +4$, nicht $-4$."}
            },
            {
                id: "sb3",
                question: "**Übergangskurve im Straßenbau**\n\nZwei gerade Fahrbahnabschnitte sollen durch eine glatte Kurve\nverbunden werden:\n- Links (für $x \\leq 0$): Die Fahrbahn liegt auf Höhe $y = 0$.\n- Rechts (für $x \\geq 2$): Die Fahrbahn liegt auf Höhe $y = 1\\,\\text{m}$.\n\nIm Bereich $0 \\leq x \\leq 2$ wird die Verbindung durch ein Polynom\n$f(x) = ax^3 + bx^2$ beschrieben (ohne linearen und konstanten Term).\n\nDamit kein Knick entsteht, müssen an den Nahtstellen $x = 0$ und $x = 2$\nsowohl der **Funktionswert** als auch die **Steigung** übereinstimmen.\n\n**Stellen Sie die Bedingungen bei $x = 2$ auf und berechne $a$ und $b$.**\n(Die Bedingungen bei $x = 0$ sind automatisch erfüllt — überleg sich warum!)\n\nGib Ihr Ergebnis als `a; b` an (als Bruch).",
                answer: "-1/4; 3/4",
                accepts: ["-1/4; 3/4","-0.25; 0.75","-0,25; 0,75","a=-1/4, b=3/4"],
                hints: ["Bei $x = 2$ muss gelten:\n$f(2) = 8a + 4b = 1$ (Anschluss an $y = 1$)\n$f'(2) = 12a + 4b = 0$ (Steigung $= 0$, weil rechts waagerecht)","Subtrahiere die Gleichungen: $(12a + 4b) - (8a + 4b) = 0 - 1$\n$4a = -1$, also $a = -\\\\frac{1}{4}$.","Einsetzen: $4b = -12 \\cdot (-\\frac{1}{4}) = 3$, also $b = \\frac{3}{4}$."],
                errorPatterns: {"1/4; 3/4":"Vorzeichen! Aus $4a = -1$ folgt $a = -\\frac{1}{4}$.","-1/4; -3/4":"$4b = -12a = -12 \\cdot (-1/4) = +3$, also $b = +\\frac{3}{4}$."}
            },
            {
                id: "sb4",
                question: "**Übergangskurve — Knickfreiheit prüfen**\n\nSie haben berechnet: $f(x) = -\\frac{1}{4}x^3 + \\frac{3}{4}x^2$.\n\nJetzt sollst Sie prüfen, ob die Kurve wirklich knickfrei an beide\ngeraden Stücke anschließt. Dafür müssen an den Nahtstellen $x = 0$\nund $x = 2$ jeweils **Funktionswert und Steigung** übereinstimmen.\n\n**Welche Aussage ist richtig?**",
                type: "choice",
                options: ["Knickfrei an beiden Stellen: $f(0) = 0$, $f'(0) = 0$, $f(2) = 1$, $f'(2) = 0$ — alles passt","Nur bei $x = 0$ knickfrei, bei $x = 2$ springt die Steigung","Nur bei $x = 2$ knickfrei, bei $x = 0$ gibt es einen Knick","An keiner Stelle knickfrei — man bräuchte ein Polynom höheren Grades"],
                correct: 0,
                hints: ["Rechnen Sie nach: $f(0) = 0$ ✓ (passt zu $y = 0$ links).\n$f'(x) = -\\\\frac{3}{4}x^2 + \\\\frac{3}{2}x$, also $f'(0) = 0$ ✓ (Steigung links ist auch $0$).","$f(2) = -2 + 3 = 1$ ✓ und $f'(2) = -3 + 3 = 0$ ✓.\nAn beiden Stellen stimmen Funktionswert UND Steigung überein — knickfrei!"],
            },
            {
                id: "sb5",
                question: "**Spannungs-Dehnungs-Diagramm**\n\nIn der Werkstoffprüfung beschreibt man das Verhalten eines Metalls unter\nZugbelastung durch ein Spannungs-Dehnungs-Diagramm. Sie modellieren den\nBereich bis zur Zugfestigkeit mit einer quadratischen Funktion:\n$$\\sigma(\\varepsilon) = a\\varepsilon^2 + b\\varepsilon$$\n\nAus dem Zugversuch kennst du:\n- Ohne Dehnung keine Spannung: $\\sigma(0) = 0$ (automatisch erfüllt ✓)\n- Bei Dehnung $\\varepsilon = 2\\,\\%$ wird die **Zugfestigkeit** $\\sigma = 400\\,\\text{MPa}$ erreicht.\n- Bei der Zugfestigkeit hat $\\sigma$ ein **Maximum**: $\\sigma'(2) = 0$.\n\n**Berechne $a$ und $b$.**\nGib Ihr Ergebnis als `a; b` an.",
                answer: "-100; 400",
                accepts: ["-100; 400","-100;400","a=-100, b=400","a=-100;b=400"],
                hints: ["Zwei Bedingungen, zwei Unbekannte:\n$\\sigma(2) = 4a + 2b = 400$\n$\\sigma'(\\varepsilon) = 2a\\varepsilon + b$, also $\\sigma'(2) = 4a + b = 0$","Subtrahiere: $(4a + 2b) - (4a + b) = 400 - 0$, also $b = 400$.\nEinsetzen: $4a + 400 = 0$, also $a = -100$."],
                errorPatterns: {"100; 400":"Vorzeichen! Aus $4a + 400 = 0$ folgt $a = -100$."}
            },
            {
                id: "sb6",
                question: "**Nichtlineare Federkennlinie**\n\nEine Spezialfeder für einen Stoßdämpfer verhält sich nicht linear.\nDie Kraft $F$ (in Newton) in Abhängigkeit vom Federweg $s$ (in cm)\nwird durch eine quadratische Funktion modelliert:\n$$F(s) = as^2 + bs + c$$\n\nIm Labor wurden drei Messpunkte aufgenommen:\n\n| Federweg $s$ (cm) | 0 | 2 | 5 |\n|---|---|---|---|\n| Kraft $F$ (N)      | 0 | 10 | 40 |\n\n**Bestimmen Sie die drei Koeffizienten $a$, $b$ und $c$.**\nGib Ihr Ergebnis als `a; b; c` an.",
                answer: "1; 3; 0",
                accepts: ["1; 3; 0","1;3;0","a=1, b=3, c=0","1, 3, 0"],
                hints: ["Setzen Sie die drei Punkte nacheinander ein:\n$F(0) = c = 0$.\n$F(2) = 4a + 2b = 10$.\n$F(5) = 25a + 5b = 40$.","Mit $c = 0$ bleiben zwei Gleichungen:\n$4a + 2b = 10$ und $25a + 5b = 40$.\nAus der ersten: $2a + b = 5$, also $b = 5 - 2a$.","Einsetzen: $25a + 5(5 - 2a) = 40$ → $25a + 25 - 10a = 40$\n→ $15a = 15$ → $a = 1$, $b = 3$, $c = 0$."],
                errorPatterns: {"0; 5; 0":"Das wäre linear ($F = 5s$). Aber $F(5) = 25 \\neq 40$ — passt nicht!","1; 3; 10":"$F(0) = c$. Da $F(0) = 0$, muss $c = 0$ sein."}
            },
            {
                id: "sb7",
                question: "**Temperaturverlauf in einem Reaktor**\n\nDie Temperatur in einem chemischen Reaktor wird durch ein kubisches\nPolynom modelliert:\n$$T(t) = at^3 + bt^2 + ct + d \\quad \\text{(°C, } t \\text{ in Stunden)}$$\n\nAus den Messdaten und der Prozesssteuerung kennst du:\n- Starttemperatur: $T(0) = 20\\,°\\text{C}$\n- Der Reaktor wird langsam hochgefahren, die Temperatur steigt anfangs\n  **nicht** sofort: $T'(0) = 0$\n- Nach $4$ Stunden wird die Maximaltemperatur $T(4) = 52\\,°\\text{C}$ gemessen.\n- Nach $6$ Stunden ist die Temperatur wieder auf dem Startwert: $T(6) = 20\\,°\\text{C}$\n\nDas sind 4 Bedingungen für 4 Unbekannte.\n\n**Bestimmen Sie die Funktionsgleichung.** Geben Sie die Koeffizienten als\n`a; b; c; d` an (ganzzahlig).",
                answer: "-1; 6; 0; 20",
                accepts: ["-1; 6; 0; 20","-1;6;0;20","a=-1, b=6, c=0, d=20","-1, 6, 0, 20"],
                hints: ["Aus $T(0) = d = 20$ und $T'(0) = c = 0$ folgt sofort: $d = 20$, $c = 0$.\nEs bleiben zwei Gleichungen für $a$ und $b$.","$T(4) = 52$: $64a + 16b + 20 = 52$, also $64a + 16b = 32$ → $4a + b = 2$.\n$T(6) = 20$: $216a + 36b + 20 = 20$, also $216a + 36b = 0$ → $6a + b = 0$.","Subtrahiere: $(6a + b) - (4a + b) = 0 - 2$, also $2a = -2$, $a = -1$.\nEinsetzen: $b = -6 \\cdot (-1) = 6$.\nErgebnis: $T(t) = -t^3 + 6t^2 + 20$."],
                errorPatterns: {"1; 6; 0; 20":"Vorzeichen! $2a = -2$, also $a = -1$.","-1; -6; 0; 20":"$b = -6a = -6 \\cdot (-1) = +6$."}
            },
            {
                id: "sb8",
                question: "**Reflexion: Wie viele Bedingungen braucht man?**\n\nSie sollen eine ganzrationale Funktion **dritten Grades** bestimmen:\n$$f(x) = ax^3 + bx^2 + cx + d$$\n\n**Wie viele Bedingungen brauchen Sie mindestens, um alle vier\nKoeffizienten eindeutig zu bestimmen?**",
                type: "choice",
                options: ["3 Bedingungen","4 Bedingungen","5 Bedingungen","Das hängt von der Aufgabe ab"],
                correct: 1,
                hints: ["Zähle die Unbekannten: $a$, $b$, $c$, $d$ — das sind 4.\nJede Bedingung (Punkt, Extremum, Steigung, ...) liefert eine Gleichung.","4 Unbekannte → 4 Gleichungen → **4 Bedingungen**.\nWichtig: Die Bedingungen müssen **voneinander unabhängig** sein!"],
            },
            {
                id: "sb9",
                question: "**Reflexion: Abhängige Bedingungen**\n\nSie modellieren eine symmetrische Brückenkontur mit\n$f(x) = ax^4 + bx^2 + c$ (nur gerade Exponenten).\n\nBedingungen:\n- Scheitelpunkt: $f(0) = 8$\n- Auflager links: $f(-5) = 0$\n- Auflager rechts: $f(5) = 0$\n\nDas sind 3 Bedingungen für 3 Unbekannte ($a$, $b$, $c$). Trotzdem\nliefert das LGS **nur 2 unabhängige Gleichungen**. Warum?",
                type: "choice",
                options: ["Weil $f(-5) = 0$ und $f(5) = 0$ dasselbe ergeben — die Funktion ist ja symmetrisch!","Weil $c = 0$ gilt","Weil die Funktion keine ungeraden Exponenten hat","Weil 3 Bedingungen nie für 3 Unbekannte reichen"],
                correct: 0,
                hints: ["Setze $x = -5$ und $x = 5$ in $f(x) = ax^4 + bx^2 + c$ ein.\nWas fällt Ihnen auf?","$f(-5) = a \\cdot 625 + b \\cdot 25 + c$ und\n$f(5) = a \\cdot 625 + b \\cdot 25 + c$.\nIdentisch! Die Symmetrie macht eine Bedingung überflüssig.\nSie brauchen einen weiteren Punkt, z.\\,B. $f(3) = 5$."],
            },
            {
                id: "sb10",
                question: "**Reflexion: Welche Bedingung gehört wozu?**\n\nSie sollen eine Funktion bestimmen, die bei $x = 3$ ein **Maximum**\nmit dem Funktionswert $5$ hat.\n\n**Welche zwei Gleichungen ergeben sich daraus?**",
                type: "choice",
                options: ["$f(3) = 5$ und $f'(3) = 5$","$f(3) = 5$ und $f'(3) = 0$","$f'(3) = 0$ und $f''(3) = 0$","$f(3) = 0$ und $f'(3) = 5$"],
                correct: 1,
                hints: ["Ein Maximum hat zwei Eigenschaften:\n1. Der **Funktionswert** ist gegeben: $f(3) = 5$\n2. Die **Steigung** ist Null (horizontale Tangente): $f'(3) = 0$","Verwechslungsgefahr: $f'(3) = 0$ heißt „Steigung Null\",\nnicht „Funktionswert Null\"! Das $f''$ brauchen Sie nur,\num zu prüfen ob es ein Maximum oder Minimum ist."],
            },
        ]
    },

    // --- Modellieren & Optimieren (AS 6) ---
    "modellierung": {
        title: "Modellieren & Optimieren",
        description: "Sie lernen, aus Messdaten mathematische Modelle zu erstellen (Regression),\nderen Güte zu beurteilen (R²), Extremwertprobleme zu lösen und\nabschnittsweise definierte Funktionen zu untersuchen.",
        explanation: "<h3>Modellieren mit Funktionen</h3>\n<p>In der Technik werden Zusammenhänge häufig durch Funktionen beschrieben.\nDabei gibt es zwei Wege:</p>\n<ol style=\"margin-left:1.5rem; line-height:2.2;\">\n  <li><strong>Regression:</strong> Aus Messdaten eine passende Funktion berechnen\n    (z.&nbsp;B. linear, quadratisch). Das <strong>Bestimmtheitsmaß R²</strong> (zwischen 0 und 1)\n    sagt Ihnen, wie gut die Funktion zu den Daten passt. Je näher an 1, desto besser.</li>\n  <li><strong>Optimierung:</strong> Extremwerte einer Modellfunktion bestimmen\n    (Maximum/Minimum), um z.&nbsp;B. den besten Arbeitspunkt zu finden.</li>\n  <li><strong>Abschnittsweise Funktionen:</strong> Verschiedene Formeln für verschiedene\n    Bereiche — wichtig ist, ob an den Nahtstellen Sprünge oder Knicke auftreten\n    (Stetigkeit, Differenzierbarkeit).</li>\n</ol>\n<div style=\"margin-top:1rem; padding:0.8rem; background:#fff3cd; border-radius:8px; color:#333;\">\n  <strong>Werkzeuge:</strong> Nutzen Sie Ihren TI-Nspire CAS für Regressionen\n  (Menü → Statistik → Regression) und zum Ableiten/Lösen.\n</div>",
        masteryThreshold: 0.7,
        tasks: [
            {
                id: "mod1",
                question: "**Widerstandsthermometer Pt100 — Lineare Regression**\n\nEin Pt100-Sensor ist ein Widerstandsthermometer, dessen elektrischer\nWiderstand sich mit der Temperatur ändert. In einem Kalibrierversuch\nwurden folgende Messwerte aufgenommen:\n\n| Temperatur $T$ (°C) | 0 | 20 | 40 | 60 | 80 | 100 |\n|---|---|---|---|---|---|---|\n| Widerstand $R$ (Ω)  | 100,0 | 107,8 | 115,5 | 123,2 | 130,9 | 138,5 |\n\nDer Zusammenhang soll durch eine lineare Funktion $R(T) = aT + b$\nmodelliert werden.\n\n**Führen Sie mit Ihrem TI-Nspire eine lineare Regression durch.**\nGeben Sie die Steigung $a$ auf vier Nachkommastellen und den\ny-Achsenabschnitt $b$ auf eine Nachkommastelle gerundet an.\n\nFormat: `a; b` (z. B. `0,1234; 56,7`)",
                answer: "0,3850; 100,1",
                accepts: ["0,3850; 100,1","0.3850; 100.1","0,385; 100,1","0.385; 100.1","0,385;100,1"],
                hints: ["Geben Sie die Daten in zwei Listen ein (Temperatur und Widerstand).\nWählen Sie dann: Menü → Statistik → Stat-Berechnungen → Lineare Regression ($y = ax + b$).","Der TI liefert: $a \\approx 0{,}3850$ und $b \\approx 100{,}07$.\nGerundet: $a = 0{,}3850$; $b = 100{,}1$."],
                errorPatterns: {"100,1; 0,385":"Reihenfolge beachten! Erst die Steigung $a$, dann der Achsenabschnitt $b$.","0,385; 100":"Der Achsenabschnitt ist $b \\approx 100{,}07$, also gerundet $100{,}1$ — nicht genau $100$."}
            },
            {
                id: "mod2",
                question: "**Bestimmtheitsmaß R² — Was sagt es aus?**\n\nFür die Pt100-Regression aus der vorigen Aufgabe liefert der TI-Nspire\nein Bestimmtheitsmaß von $R^2 = 0{,}99999$. Ein Kollege sagt: „Dann\nist das Modell perfekt, da kann nichts schiefgehen.\"\n\nSie wissen es besser. **Welche Aussage ist korrekt?**",
                type: "choice",
                options: ["$R^2 \\approx 1$ bedeutet, dass die lineare Funktion die Messdaten fast perfekt beschreibt — aber Extrapolation weit über den Messbereich hinaus ist trotzdem riskant.","$R^2 \\approx 1$ beweist, dass der Zusammenhang exakt linear ist und für alle Temperaturen gilt.","$R^2$ sagt nur etwas über die Anzahl der Messpunkte aus, nicht über die Modellgüte.","Ein $R^2$ so nahe an 1 deutet auf einen Messfehler hin."],
                correct: 0,
                hints: ["$R^2$ misst, welcher Anteil der Streuung in den Daten durch das Modell\nerklärt wird. $R^2 = 1$ heißt: alle Punkte liegen exakt auf der Geraden.","Aber: Eine gute Anpassung im Messbereich garantiert nicht, dass das Modell\nauch außerhalb gilt! Der Pt100 ist z. B. bei sehr hohen Temperaturen\nnicht mehr linear."],
            },
            {
                id: "mod3",
                question: "**Betondruckfestigkeit — Quadratische Regression**\n\nIn der Werkstoffprüfung wird untersucht, wie die 28-Tage-Druckfestigkeit\nvon Beton vom Wasser-Zement-Wert (w/z-Wert) abhängt. Je höher der\nw/z-Wert, desto weniger fest ist der Beton — aber der Zusammenhang\nist nicht ganz linear. Folgende Messwerte liegen vor:\n\n| w/z-Wert          | 0,35 | 0,40 | 0,45 | 0,50 | 0,55 | 0,60 | 0,65 |\n|---|---|---|---|---|---|---|---|\n| Druckfestigkeit (MPa) | 57   | 49   | 43   | 37   | 32   | 29   | 25   |\n\n**a)** Führen Sie sowohl eine lineare als auch eine quadratische Regression durch.\nNotieren Sie die $R^2$-Werte beider Modelle (auf vier Nachkommastellen).\n\n**b)** Welches Modell passt besser? Begründen Sie anhand von $R^2$.\n\nGeben Sie die beiden $R^2$-Werte an im Format: `R²_lin; R²_quad`",
                answer: "0,9783; 0,9990",
                accepts: ["0,9783; 0,9990","0.9783; 0.9990","0,978; 0,999","0.978; 0.999","0,9783;0,9990"],
                hints: ["Geben Sie die Daten ein und führen Sie nacheinander eine lineare\nRegression ($y = ax + b$) und eine quadratische Regression\n($y = ax^2 + bx + c$) durch. Notieren Sie jeweils $R^2$.","Linear: $R^2 \\approx 0{,}9783$. Quadratisch: $R^2 \\approx 0{,}9990$.\nDas quadratische Modell hat ein höheres $R^2$ und beschreibt die\nDaten deutlich besser — die leichte Krümmung wird eingefangen."],
                errorPatterns: {"0,9990; 0,9783":"Reihenfolge! Erst $R^2$ der linearen, dann der quadratischen Regression."}
            },
            {
                id: "mod4",
                question: "**Federkennlinie — Prognose mit Regression**\n\nIm Physiklabor wird eine Schraubenfeder mit verschiedenen Massen\nbelastet und die resultierende Federlänge gemessen:\n\n| Masse $m$ (g)      | 0    | 50   | 100  | 150  | 200  | 250  | 300  |\n|---|---|---|---|---|---|---|---|\n| Federlänge $L$ (cm) | 15,0 | 16,2 | 17,5 | 18,7 | 20,0 | 21,2 | 22,5 |\n\nEine lineare Regression liefert $L(m) = 0{,}025 \\cdot m + 15{,}0$\nmit $R^2 = 0{,}9999$.\n\nDie Feder soll in einem Messgerät eingesetzt werden, das eine\nFederlänge von exakt $25{,}0\\,\\text{cm}$ benötigt.\n\n**Berechnen Sie mithilfe der Regressionsfunktion, welche Masse\ndafür angehängt werden muss.** Geben Sie das Ergebnis in Gramm an.",
                answer: "400",
                accepts: ["400","400 g","400g","400,0","m=400"],
                hints: ["Setzen Sie $L = 25{,}0$ in die Regressionsgleichung ein:\n$25{,}0 = 0{,}025 \\cdot m + 15{,}0$","Umstellen: $0{,}025 \\cdot m = 10{,}0$, also $m = \\frac{10{,}0}{0{,}025} = 400\\,\\text{g}$."],
                errorPatterns: {"10":"Das ist die Differenz $25 - 15 = 10$. Teilen Sie noch durch die Steigung $0{,}025$!","0,25":"Aufpassen: $m = \\frac{10}{0{,}025}$, nicht $10 \\cdot 0{,}025$."}
            },
            {
                id: "mod5",
                question: "**Maximale Leistung eines Solarmoduls — Geführt**\n\nDie elektrische Leistung $P$ (in Watt) eines Solarmoduls hängt von\nder Betriebsspannung $U$ (in Volt) ab. Im relevanten Bereich gilt\ndas Modell:\n$$P(U) = -0{,}5\\,U^2 + 6\\,U$$\n\nUm den **Maximum Power Point (MPP)** zu finden, müssen Sie das\nMaximum dieser Funktion bestimmen.\n\n**Schritt 1:** Berechnen Sie $P'(U)$ und setzen Sie $P'(U) = 0$.\n\n**Bei welcher Spannung $U$ wird die maximale Leistung erreicht?**\nGeben Sie den Wert in Volt an.",
                answer: "6",
                accepts: ["6","6 V","6V","U=6","U = 6"],
                hints: ["$P'(U) = -U + 6$. Setzen Sie gleich Null: $-U + 6 = 0$.","$U = 6\\,\\text{V}$. Da $P''(U) = -1 < 0$, ist dies tatsächlich ein Maximum."],
                errorPatterns: {"18":"Das ist $P(6) = 18\\,\\text{W}$, also die maximale Leistung. Gefragt war die Spannung!","-6":"Vorzeichen! Aus $-U + 6 = 0$ folgt $U = +6$."}
            },
            {
                id: "mod6",
                question: "**Optimale Betriebstemperatur einer Gasturbine**\n\nDer thermische Wirkungsgrad $\\eta$ (in Prozent) einer Gasturbine\nwird in Abhängigkeit von der Eintrittstemperatur $T$ (in °C) durch\nfolgende Modellfunktion beschrieben:\n$$\\eta(T) = -0{,}002\\,T^2 + 1{,}2\\,T - 100$$\n\nDiese Funktion gilt im Bereich $100 \\leq T \\leq 500\\,°\\text{C}$.\nDer Hersteller möchte die Temperatur finden, bei der der\nWirkungsgrad maximal ist.\n\n**Bestimmen Sie die optimale Eintrittstemperatur und den\nzugehörigen maximalen Wirkungsgrad.**\n\nFormat: `T_opt; η_max` (z. B. `250; 75`)",
                answer: "300; 80",
                accepts: ["300; 80","300;80","T=300; η=80","300 °C; 80 %","300; 80,0"],
                hints: ["$\\eta'(T) = -0{,}004\\,T + 1{,}2$. Setzen Sie $\\eta'(T) = 0$:\n$-0{,}004\\,T + 1{,}2 = 0$, also $T = \\frac{1{,}2}{0{,}004}$.","$T_{\\text{opt}} = 300\\,°\\text{C}$.\nEinsetzen: $\\eta(300) = -0{,}002 \\cdot 90000 + 1{,}2 \\cdot 300 - 100\n= -180 + 360 - 100 = 80\\,\\%$."],
                errorPatterns: {"300; 260":"Rechenfehler! $\\eta(300) = -180 + 360 - 100 = 80$, nicht $260$.","30; 80":"Einheiten prüfen! $T = \\frac{1{,}2}{0{,}004} = 300$, nicht $30$."}
            },
            {
                id: "mod7",
                question: "**Stückkosten in der CNC-Fertigung**\n\nEin Unternehmen produziert Präzisionsbauteile auf einer CNC-Fräse.\nDie Stückkosten $K$ (in Euro) hängen von der Produktionsmenge $x$\n(in Tausend Stück pro Monat) ab. Durch Datenanalyse wurde\nfolgendes Modell ermittelt:\n$$K(x) = 2x^3 - 24x^2 + 90x + 50 \\quad (1 \\leq x \\leq 8)$$\n\nBei kleinen Mengen sind die Kosten hoch (Rüstkosten), bei mittleren\nMengen sinken sie durch Skaleneffekte, und bei sehr großen Mengen\nsteigen sie wieder (Überstunden, Verschleiß).\n\n**Bestimmen Sie die Produktionsmenge, bei der die Stückkosten\nminimal sind, und die zugehörigen minimalen Stückkosten.**\n\nFormat: `x; K_min` (z. B. `3; 120`)",
                answer: "5; 150",
                accepts: ["5; 150","5;150","x=5; K=150","5000; 150","5; 150 €"],
                hints: ["$K'(x) = 6x^2 - 48x + 90$. Setzen Sie $K'(x) = 0$:\n$6x^2 - 48x + 90 = 0$, also $x^2 - 8x + 15 = 0$.","$(x - 3)(x - 5) = 0$, also $x_1 = 3$ und $x_2 = 5$.\nPrüfen Sie mit $K''(x) = 12x - 48$:\n$K''(3) = -12 < 0$ → Maximum bei $x = 3$.\n$K''(5) = 12 > 0$ → **Minimum** bei $x = 5$.","$K(5) = 250 - 600 + 450 + 50 = 150\\,€$."],
                errorPatterns: {"3; 158":"Bei $x = 3$ liegt ein lokales Maximum ($K'' < 0$), kein Minimum! Prüfen Sie $x = 5$.","5; 200":"Nachrechnen: $K(5) = 2 \\cdot 125 - 24 \\cdot 25 + 90 \\cdot 5 + 50 = 250 - 600 + 450 + 50 = 150$."}
            },
            {
                id: "mod8",
                question: "**Optimaler Querschnitt eines Kabelkanals**\n\nFür eine Industrieanlage soll ein rechteckiger Kabelkanal aus einem\nBlechstreifen gebogen werden. Der Blechstreifen hat eine Breite von\n$40\\,\\text{cm}$. Daraus wird ein offener Kanal (U-Profil) gebogen:\nZwei Seitenwände der Höhe $a$ und ein Boden der Breite $b$.\n\nDa der gesamte Blechstreifen verwendet wird, gilt:\n$2a + b = 40\\,\\text{cm}$.\n\n**Bestimmen Sie die Maße $a$ und $b$, bei denen die\nQuerschnittsfläche $A = a \\cdot b$ maximal wird.**\n\nFormat: `a; b; A_max` (in cm bzw. cm²)",
                answer: "10; 20; 200",
                accepts: ["10; 20; 200","10;20;200","a=10, b=20, A=200","10 cm; 20 cm; 200 cm²"],
                hints: ["Drücken Sie $b$ durch $a$ aus: $b = 40 - 2a$.\nDann: $A(a) = a \\cdot (40 - 2a) = 40a - 2a^2$.","$A'(a) = 40 - 4a = 0$, also $a = 10\\,\\text{cm}$.\nDann $b = 40 - 20 = 20\\,\\text{cm}$ und $A = 10 \\cdot 20 = 200\\,\\text{cm}^2$.","$A''(a) = -4 < 0$ bestätigt: es ist ein Maximum."],
                errorPatterns: {"20; 20; 400":"Wenn $a = 20$, dann $b = 40 - 40 = 0$ — kein Boden! Die Nebenbedingung ist $2a + b = 40$.","10; 10; 100":"$b = 40 - 2a = 40 - 20 = 20$, nicht $10$."}
            },
            {
                id: "mod9",
                question: "**Temperaturverlauf im Härteofen — Stetigkeit**\n\nBeim Härten von Stahl durchläuft das Werkstück drei Phasen.\nDie Temperatur $T$ (in °C) wird abschnittsweise modelliert:\n\n$$T(t) = \\begin{cases}\n50t & \\text{für } 0 \\leq t \\leq 4 \\quad \\text{(Aufheizen)} \\\\\n200 & \\text{für } 4 < t \\leq 8 \\quad \\text{(Halten)} \\\\\n-25t + 400 & \\text{für } 8 < t \\leq 16 \\quad \\text{(Abkühlen)}\n\\end{cases}$$\n\nDabei ist $t$ die Zeit in Stunden.\n\n**Ist die Temperaturfunktion stetig? Prüfen Sie die Nahtstellen\n$t = 4$ und $t = 8$.**",
                type: "choice",
                options: ["Stetig an beiden Stellen: $T$ springt nirgends.","Unstetig bei $t = 4$, stetig bei $t = 8$.","Stetig bei $t = 4$, unstetig bei $t = 8$.","Unstetig an beiden Stellen."],
                correct: 0,
                hints: ["Prüfen Sie $t = 4$: Von links: $50 \\cdot 4 = 200$.\nVon rechts: $T = 200$. → $200 = 200$ ✓","Prüfen Sie $t = 8$: Von links: $T = 200$.\nVon rechts: $-25 \\cdot 8 + 400 = 200$. → $200 = 200$ ✓\nDie Funktion ist an beiden Nahtstellen stetig (kein Sprung)."],
            },
            {
                id: "mod10",
                question: "**Spannungs-Dehnungs-Diagramm — Differenzierbarkeit**\n\nBei einem Zugversuch wird das Verhalten eines Baustahls\nabschnittsweise modelliert:\n\n$$\\sigma(\\varepsilon) = \\begin{cases}\n100\\,\\varepsilon & \\text{für } 0 \\leq \\varepsilon \\leq 3 \\quad \\text{(elastisch)} \\\\\n-5(\\varepsilon - 7)^2 + 380 & \\text{für } 3 < \\varepsilon \\leq 10 \\quad \\text{(plastisch)}\n\\end{cases}$$\n\nDabei ist $\\varepsilon$ die Dehnung in ‰ und $\\sigma$ die Spannung in MPa.\n\n**a)** Prüfen Sie die Stetigkeit bei $\\varepsilon = 3$: Stimmen die\nFunktionswerte von links und rechts überein?\n\n**b)** Prüfen Sie die Differenzierbarkeit bei $\\varepsilon = 3$: Stimmen\ndie Ableitungen von links und rechts überein?\n\n**c)** Bestimmen Sie die maximale Spannung $\\sigma_{\\max}$ und die\nzugehörige Dehnung.\n\nFormat: `stetig ja/nein; differenzierbar ja/nein; σ_max; ε_max`",
                answer: "ja; nein; 380; 7",
                accepts: ["ja; nein; 380; 7","ja;nein;380;7","stetig; nicht differenzierbar; 380; 7"],
                hints: ["Stetigkeit: $\\sigma_1(3) = 100 \\cdot 3 = 300$.\n$\\sigma_2(3) = -5(3 - 7)^2 + 380 = -5 \\cdot 16 + 380 = 300$. ✓ Stetig!","Differenzierbarkeit: $\\sigma_1'(\\varepsilon) = 100$, also $\\sigma_1'(3) = 100$.\n$\\sigma_2'(\\varepsilon) = -10(\\varepsilon - 7)$, also $\\sigma_2'(3) = -10 \\cdot (-4) = 40$.\n$100 \\neq 40$ → **nicht differenzierbar** (Knick!).","Maximum: $\\sigma_2'(\\varepsilon) = 0$ bei $\\varepsilon = 7$.\n$\\sigma_2(7) = -5 \\cdot 0 + 380 = 380\\,\\text{MPa}$."],
                errorPatterns: {"ja; ja; 380; 7":"Ableitungen vergleichen! $\\sigma_1'(3) = 100$, aber $\\sigma_2'(3) = 40$ → nicht gleich → Knick!","nein; nein; 380; 7":"Beide Funktionswerte bei $\\varepsilon = 3$ sind $300$ — die Funktion IST stetig."}
            },
            {
                id: "mod11",
                question: "**CNC-Werkstück — Höhenprofil analysieren**\n\nEin CNC-gefrästes Werkstück hat ein Höhenprofil, das durch zwei\nFunktionen beschrieben wird:\n\n$$h(x) = \\begin{cases}\nx^2 & \\text{für } 0 \\leq x \\leq 1 \\\\\n-(x - 2)^2 + 2 & \\text{für } 1 < x \\leq 3\n\\end{cases}$$\n\nDabei ist $x$ die horizontale Position in cm und $h$ die Höhe in mm.\nFür die Qualitätskontrolle müssen Sie das Profil vollständig\nuntersuchen.\n\n**a)** Ist das Profil bei $x = 1$ stetig und differenzierbar?\n\n**b)** Bestimmen Sie die maximale Höhe des Werkstücks und die\nPosition, an der sie auftritt.\n\n**c)** Welche Höhe hat das Werkstück am rechten Rand ($x = 3$)?\n\nFormat: `stetig ja/nein; diff. ja/nein; h_max; x_max; h(3)`",
                answer: "ja; ja; 2; 2; 1",
                accepts: ["ja; ja; 2; 2; 1","ja;ja;2;2;1","stetig; differenzierbar; 2; 2; 1"],
                hints: ["Stetigkeit bei $x = 1$:\n$h_1(1) = 1^2 = 1$ und $h_2(1) = -(1-2)^2 + 2 = -1 + 2 = 1$. ✓","Differenzierbarkeit bei $x = 1$:\n$h_1'(x) = 2x$, also $h_1'(1) = 2$.\n$h_2'(x) = -2(x-2)$, also $h_2'(1) = -2 \\cdot (-1) = 2$. ✓\nStetig UND differenzierbar!","Maximum von $h_2$: $h_2'(x) = 0$ bei $x = 2$.\n$h_2(2) = 0 + 2 = 2\\,\\text{mm}$.\nAm Rand: $h_2(3) = -(3-2)^2 + 2 = -1 + 2 = 1\\,\\text{mm}$."],
                errorPatterns: {"ja; nein; 2; 2; 1":"Ableitungen nachrechnen: $h_1'(1) = 2$ und $h_2'(1) = 2$ — sie SIND gleich!","ja; ja; 1; 1; 1":"Bei $x = 1$ ist $h = 1$, aber das ist kein Maximum. Untersuchen Sie $h_2$ auf Extrema!"}
            },
            {
                id: "mod12",
                question: "**Extrapolation — Risiken erkennen**\n\nSie haben eine quadratische Regressionsfunktion für die\nBetondruckfestigkeit in Abhängigkeit vom w/z-Wert bestimmt.\nDie Messdaten lagen im Bereich $0{,}35 \\leq w/z \\leq 0{,}65$.\n\nIhr Auftraggeber fragt: „Was ergibt das Modell für $w/z = 1{,}0$?\"\n\nSie rechnen nach und erhalten einen negativen Wert für die\nDruckfestigkeit.\n\n**Welche Schlussfolgerung ist fachlich korrekt?**",
                type: "choice",
                options: ["Das Modell ist falsch und muss komplett verworfen werden.","Negative Druckfestigkeit ist physikalisch unmöglich — das Modell darf nicht so weit über den Messbereich hinaus extrapoliert werden.","Negative Druckfestigkeit bedeutet, dass der Beton unter Zug steht.","Man muss einfach den Betrag nehmen: $|f(1{,}0)|$."],
                correct: 1,
                hints: ["Polynomfunktionen können beliebig große oder kleine Werte annehmen.\nAußerhalb des Messbereichs gibt es keine Garantie, dass das Modell\ndie Realität noch beschreibt.","Korrekt ist: Das Modell liefert im Messbereich gute Ergebnisse\n($R^2$ hoch), aber bei $w/z = 1{,}0$ ist es nicht mehr gültig.\nDruckfestigkeit kann physikalisch nicht negativ werden!"],
            },
            {
                id: "mod13",
                question: "**Modellvergleich — Welche Funktion passt?**\n\nEin Temperatursensor liefert über 24 Stunden folgende\nAußentemperaturen (vereinfacht):\n\n| Zeit $t$ (h) | 0 | 4 | 8 | 12 | 16 | 20 | 24 |\n|---|---|---|---|---|---|---|---|\n| Temperatur $T$ (°C) | 5 | 3 | 8 | 18 | 16 | 9 | 5 |\n\nEin Kollege schlägt ein Polynom 6. Grades vor (geht durch alle Punkte,\n$R^2 = 1$). Ein anderer schlägt ein quadratisches Modell vor\n($R^2 = 0{,}72$).\n\n**Nennen Sie zwei Argumente, warum das Polynom 6. Grades trotz\n$R^2 = 1$ problematisch sein kann, und ein Argument für das\neinfachere quadratische Modell.**\n\n*(Freitext — formulieren Sie in ganzen Sätzen.)*",
                answer: "1) Ein Polynom 6. Grades passt sich den Daten exakt an (Overfitting),\nschwingt aber zwischen den Messpunkten möglicherweise stark — es\nbildet physikalisch unsinnige Zwischenwerte.\n2) Prognosen außerhalb des Messbereichs sind mit hohem Grad extrem\nunzuverlässig, da das Polynom schnell divergiert.\n3) Das quadratische Modell ist robuster: Es glättet Messrauschen\nund liefert einen plausiblen Trendverlauf.\n",
                accepts: [],
                input_mode: "speech",
                hints: ["Denken Sie an **Overfitting**: Ein Polynom hohen Grades kann die Daten\nexakt treffen, aber zwischen den Punkten wild schwanken.","Zwei Probleme: (1) Zwischen den Messpunkten kann das Polynom\nunrealistische Werte annehmen (z. B. $-10\\,°\\text{C}$ mitten am Tag).\n(2) Außerhalb von $0 \\leq t \\leq 24$ divergiert es extrem.","Vorteil des einfacheren Modells: Es glättet Messrauschen und gibt\nden generellen Trend wieder, auch wenn einzelne Punkte nicht exakt\ngetroffen werden."],
            },
            {
                id: "mod14",
                question: "**Reflexion: Grenzen ganzrationaler Modelle**\n\nIn dieser Unit haben Sie verschiedene technische Zusammenhänge mit\nganzrationalen Funktionen (Polynomen) modelliert: Widerstand vs.\nTemperatur, Betondruckfestigkeit, Spannungs-Dehnungs-Diagramme,\nTemperaturverläufe.\n\n**Nennen Sie je zwei Vorteile und zwei Nachteile/Grenzen der\nModellierung mit ganzrationalen Funktionen.**\n\n*(Freitext — formulieren Sie in ganzen Sätzen.)*",
                answer: "Vorteile:\n1) Polynome lassen sich leicht ableiten und integrieren — Extrema,\nWendepunkte und Flächen sind analytisch berechenbar.\n2) Regression mit Polynomen ist mit jedem CAS oder Taschenrechner\ndurchführbar — die Methode ist universell verfügbar.\n\nNachteile/Grenzen:\n1) Polynome wachsen für große |x| über alle Grenzen — sie können\nphysikalische Sättigungseffekte oder Grenzwerte nicht darstellen.\n2) Hoher Polynomgrad führt zu Overfitting: Das Modell passt perfekt\nzu den Daten, aber schwingt dazwischen und liefert keine sinnvollen\nPrognosen.\n",
                accepts: [],
                input_mode: "speech",
                hints: ["**Vorteile:** Denken Sie an die mathematische Handhabbarkeit\n(Ableitung, Integration) und die Verfügbarkeit der Werkzeuge\n(CAS, Taschenrechner).","**Nachteile:** Was passiert bei großen $x$-Werten?\nKönnen Polynome Sättigungseffekte oder periodische Vorgänge\n(z. B. Temperaturverlauf über mehrere Tage) abbilden?","Beispiel: Der Pt100-Widerstand ist im Messbereich linear, aber\nbei sehr hohen Temperaturen krümmt sich die Kennlinie — ein\nPolynom kann das nur mit hohem Grad annähern, und dann droht\nOverfitting."],
            },
        ]
    },

    // --- Komplexe Modellierung (AS 6) ---
    "extremwert": {
        title: "Komplexe Modellierung",
        description: "Die letzte inhaltliche Unit vor dem Abschlusstest: Sie lösen eigenständig\nExtremwertaufgaben im Sachkontext, wählen geeignete Modelle und bewerten\nderen Grenzen. Wenig Hilfestellung — Sie zeigen, was Sie können!",
        explanation: "<h3>Vorgehen bei Extremwertaufgaben</h3>\n<ol style=\"margin-left:1.5rem; line-height:2.2;\">\n  <li><strong>Zielgröße identifizieren:</strong> Was soll maximiert/minimiert werden?</li>\n  <li><strong>Hauptbedingung aufstellen:</strong> Formel für die Zielgröße</li>\n  <li><strong>Nebenbedingung nutzen:</strong> Eine Variable eliminieren → Zielfunktion in einer Variablen</li>\n  <li><strong>Ableiten, Nullsetzen, Lösen:</strong> $f'(x) = 0$ → kritische Stelle(n)</li>\n  <li><strong>Art des Extremums prüfen:</strong> $f''(x) < 0$ → Maximum, $f''(x) > 0$ → Minimum</li>\n  <li><strong>Ergebnis interpretieren:</strong> Einheiten, Plausibilität, Definitionsbereich</li>\n</ol>\n<div style=\"margin-top:1rem; padding:0.8rem; background:#fff3cd; border-radius:8px; color:#333;\">\n  <strong>Tipp:</strong> Fertigen Sie immer eine Skizze an! Sie hilft, die Nebenbedingung zu finden.\n</div>",
        masteryThreshold: 0.7,
        tasks: [
            {
                id: "ex1",
                question: "**Solarfeld an einer Gebäudewand**\n\nAuf dem Dach eines Industriegebäudes soll ein rechteckiges Solarfeld\ninstalliert werden. Eine Seite des Feldes liegt direkt an der Gebäudewand\n(dort ist kein Zaun nötig). Für die drei übrigen Seiten stehen insgesamt\n$120\\,\\text{m}$ Montageprofile zur Verfügung.\n\nBezeichnen Sie die Seite senkrecht zur Wand mit $x$ und die Seite\nparallel zur Wand mit $y$.\n\n**Bestimmen Sie die Maße $x$ und $y$, bei denen die Fläche des\nSolarfeldes maximal wird.**\n\nGeben Sie Ihr Ergebnis als `x; y` an (in Metern).",
                answer: "30; 60",
                accepts: ["30; 60","30;60","x=30, y=60","30 m; 60 m"],
                hints: ["Die Nebenbedingung lautet: $2x + y = 120$, also $y = 120 - 2x$.\nDie Zielfunktion ist die Fläche: $A(x) = x \\cdot y = x(120 - 2x)$.","$A(x) = 120x - 2x^2$.\n$A'(x) = 120 - 4x = 0$ → $x = 30$.\n$A''(x) = -4 < 0$ → Maximum.","$y = 120 - 2 \\cdot 30 = 60$. Die maximale Fläche beträgt $A = 30 \\cdot 60 = 1800\\,\\text{m}^2$."],
                errorPatterns: {"60; 30":"Prüfen Sie die Zuordnung: $x$ ist die Seite senkrecht zur Wand (kommt zweimal vor), $y$ parallel.","40; 40":"Das wäre ein Quadrat, aber die optimale Form ist hier kein Quadrat, weil eine Seite fehlt."}
            },
            {
                id: "ex2",
                question: "**Entwässerungskanal aus Blech**\n\nIn einer Produktionshalle soll ein offener Entwässerungskanal mit\nrechteckigem Querschnitt aus einem $30\\,\\text{cm}$ breiten Blechstreifen\ngebogen werden. Dazu werden links und rechts die Ränder senkrecht\nnach oben gebogen.\n\nBezeichnen Sie die Höhe der hochgebogenen Seiten mit $h$ (in cm).\nDie Breite des Kanalbodens ist dann $b = 30 - 2h$.\n\n**Welche Höhe $h$ ergibt den größten Querschnitt?**\nGeben Sie $h$ in cm an.",
                answer: "7,5",
                accepts: ["7,5","7.5","7,5 cm","7.5 cm","15/2"],
                hints: ["Der Querschnitt (Fläche) ist $A(h) = h \\cdot (30 - 2h) = 30h - 2h^2$.\nDefinitionsbereich: $0 < h < 15$.","$A'(h) = 30 - 4h = 0$ → $h = 7{,}5\\,\\text{cm}$.\n$A''(h) = -4 < 0$ → Maximum.","Bodenbreite: $b = 30 - 15 = 15\\,\\text{cm}$. Maximaler Querschnitt: $A = 7{,}5 \\cdot 15 = 112{,}5\\,\\text{cm}^2$."],
                errorPatterns: {"10":"$A'(10) = 30 - 40 = -10 \\neq 0$. Leiten Sie $A(h) = 30h - 2h^2$ ab und setzen Sie gleich Null.","15":"Das wäre $h = 15\\,\\text{cm}$ — dann bleibt keine Bodenbreite übrig! Definitionsbereich beachten: $0 < h < 15$."}
            },
            {
                id: "ex3",
                question: "**Wirtschaftliche Dämmstärke**\n\nBei der energetischen Sanierung eines Laborgebäudes muss die optimale\nDämmstoffdicke bestimmt werden. Dickere Dämmung spart Heizkosten,\nverursacht aber höhere Materialkosten.\n\nDie **jährlichen Heizkosten** pro Quadratmeter Wandfläche sinken\numgekehrt proportional zur Dämmdicke $d$ (in cm):\n$$K_H(d) = \\frac{800}{d} \\quad \\text{(€/m}^2\\text{·Jahr)}$$\n\nDie **jährlichen Dämmkosten** (Material + Amortisation) steigen\nproportional:\n$$K_D(d) = 8d \\quad \\text{(€/m}^2\\text{·Jahr)}$$\n\n**Bestimmen Sie die Dämmdicke $d$, bei der die Gesamtkosten\n$K(d) = K_H(d) + K_D(d)$ minimal werden.**\n\nGeben Sie $d$ in cm und $K_{\\min}$ in €/(m²·Jahr) an, im Format `d; K_min`.",
                answer: "10; 160",
                accepts: ["10; 160","10;160","10 cm; 160","d=10, K=160","10 cm; 160 €"],
                hints: ["$K(d) = \\frac{800}{d} + 8d$.\nAbleiten: $K'(d) = -\\frac{800}{d^2} + 8$.","$K'(d) = 0$: $\\frac{800}{d^2} = 8$ → $d^2 = 100$ → $d = 10\\,\\text{cm}$.\n$K''(d) = \\frac{1600}{d^3} > 0$ → Minimum.","$K_{\\min} = \\frac{800}{10} + 8 \\cdot 10 = 80 + 80 = 160\\,\\text{€/(m}^2\\text{·Jahr)}$."],
                errorPatterns: {"10; 80":"Sie haben nur eine der beiden Kostenarten berechnet. $K_{\\min} = K_H(10) + K_D(10) = 80 + 80 = 160$.","100; 160":"$d^2 = 100$ → $d = \\sqrt{100} = 10$, nicht $100$!"}
            },
            {
                id: "ex4",
                question: "**Zylindrische Chemikaliendose**\n\nFür ein Labor sollen zylindrische Dosen mit einem Fassungsvermögen\nvon $V = 500\\,\\text{cm}^3$ hergestellt werden. Um Material zu sparen,\nsoll die Oberfläche möglichst klein sein. Die Dose hat einen Deckel\nund einen Boden.\n\n**Bestimmen Sie Radius $r$ und Höhe $h$ der optimalen Dose.**\n\n*Hinweis:* Oberfläche des Zylinders: $O = 2\\pi r^2 + 2\\pi r h$.\n\nGeben Sie Ihr Ergebnis als `r; h` an (gerundet auf eine Dezimalstelle, in cm).",
                answer: "4,3; 8,6",
                accepts: ["4,3; 8,6","4.3; 8.6","4,3;8,6","4.3;8.6","4,3 cm; 8,6 cm"],
                hints: ["Nebenbedingung: $V = \\pi r^2 h = 500$ → $h = \\frac{500}{\\pi r^2}$.\nEinsetzen in die Oberfläche: $O(r) = 2\\pi r^2 + 2\\pi r \\cdot \\frac{500}{\\pi r^2} = 2\\pi r^2 + \\frac{1000}{r}$.","$O'(r) = 4\\pi r - \\frac{1000}{r^2} = 0$ → $4\\pi r^3 = 1000$ → $r^3 = \\frac{250}{\\pi}$ → $r = \\sqrt[3]{\\frac{250}{\\pi}}$.","$r \\approx 4{,}3\\,\\text{cm}$, $h = \\frac{500}{\\pi \\cdot 4{,}3^2} \\approx 8{,}6\\,\\text{cm}$.\nEs gilt $h = 2r$ — die optimale Dose ist so hoch wie breit (Durchmesser)!"],
                errorPatterns: {"4,3; 4,3":"Verwechslung: $h = 2r$, nicht $h = r$. Setzen Sie $r$ in $h = \\frac{500}{\\pi r^2}$ ein.","8,6; 4,3":"Radius und Höhe vertauscht! $r \\approx 4{,}3$ und $h \\approx 8{,}6$."}
            },
            {
                id: "ex5",
                question: "**Zylindrischer Lagertank**\n\nFür eine Produktionsanlage wird ein stehender, zylindrischer Lagertank\nmit einem Volumen von $V = 1\\,\\text{m}^3$ ($= 1000$ Liter) benötigt.\nDer Tank hat einen Boden und einen Deckel. Die Herstellungskosten\nsind proportional zur Oberfläche.\n\n**Bestimmen Sie das Verhältnis $\\dfrac{h}{r}$ beim materialoptimalen Tank.**\n\n*Diesen Aufgabentyp kennen Sie bereits von der Dose — hier ohne Zahlenwerte,\ndafür allgemein.*\n\nGeben Sie $\\dfrac{h}{r}$ als ganze Zahl an.",
                answer: "2",
                accepts: ["2","h/r=2","h/r = 2"],
                hints: ["Wie bei der Dose: $V = \\pi r^2 h$ → $h = \\frac{V}{\\pi r^2}$.\n$O(r) = 2\\pi r^2 + \\frac{2V}{r}$.","$O'(r) = 4\\pi r - \\frac{2V}{r^2} = 0$ → $r^3 = \\frac{V}{2\\pi}$ → $r = \\left(\\frac{V}{2\\pi}\\right)^{1/3}$.\nDann $h = \\frac{V}{\\pi r^2}$.","$\\frac{h}{r} = \\frac{V}{\\pi r^3} = \\frac{V}{\\pi \\cdot \\frac{V}{2\\pi}} = 2$.\nUnabhängig vom Volumen gilt: $h = 2r$ (Höhe = Durchmesser)."],
                errorPatterns: {"1":"Das wäre $h = r$, also Höhe = Radius. Rechnen Sie $\\frac{h}{r} = \\frac{V}{\\pi r^3}$ mit $r^3 = \\frac{V}{2\\pi}$ aus."}
            },
            {
                id: "ex6",
                question: "**Rohrleitung zu einer Offshore-Plattform**\n\nEine Gasleitung soll von einer Offshore-Plattform $P$ zu einer\nVerarbeitungsanlage $A$ an der Küste verlegt werden. Die Plattform\nliegt $3\\,\\text{km}$ vor der Küste. Die Anlage liegt $6\\,\\text{km}$\nentlang der Küste vom nächstgelegenen Küstenpunkt $K$ entfernt.\n\nDie Leitung führt zunächst unter Wasser vom Punkt $P$ schräg zu\neinem Anlandepunkt $X$ an der Küste und dann an Land von $X$ zu $A$.\nBezeichnen Sie den Abstand $\\overline{KX} = x$ (in km).\n\nKosten:\n- Unterwasser: $800\\,\\text{€/m}$\n- An Land: $400\\,\\text{€/m}$\n\n**Bei welchem Wert von $x$ sind die Gesamtkosten minimal?**\n\nGeben Sie $x$ gerundet auf zwei Dezimalstellen an (in km).\n\n*Fertigen Sie unbedingt eine Skizze an!*",
                answer: "1,73",
                accepts: ["1,73","1.73","1,73 km","1.73 km","sqrt(3)","√3"],
                hints: ["Unterwasserstrecke: $\\overline{PX} = \\sqrt{9 + x^2}$ (Pythagoras).\nLandstrecke: $\\overline{XA} = 6 - x$.\nKosten: $K(x) = 800\\sqrt{9 + x^2} + 400(6 - x)$ (in €/m · km = k€).","$K'(x) = \\frac{800x}{\\sqrt{9 + x^2}} - 400 = 0$\n→ $800x = 400\\sqrt{9 + x^2}$ → $2x = \\sqrt{9 + x^2}$.\nQuadrieren: $4x^2 = 9 + x^2$ → $3x^2 = 9$ → $x = \\sqrt{3}$.","$x = \\sqrt{3} \\approx 1{,}73\\,\\text{km}$. Gesamtkosten: $K = 800 \\cdot 2\\sqrt{3} + 400(6 - \\sqrt{3}) \\approx 4478\\,\\text{k€}$."],
                errorPatterns: {"0":"Bei $x = 0$ wäre die Unterwasserstrecke $3\\,\\text{km}$ und die Landstrecke $6\\,\\text{km}$ — das ist nicht optimal.","3":"Haben Sie vergessen zu quadrieren? Aus $3x^2 = 9$ folgt $x^2 = 3$, also $x = \\sqrt{3} \\approx 1{,}73$."}
            },
            {
                id: "ex7",
                question: "**Stückkosten in der Fertigung**\n\nDie Gesamtkosten für die Produktion von $x$ Bauteilen werden durch\nfolgende Funktion beschrieben:\n$$K(x) = 2x^2 + 50x + 1800 \\quad \\text{(€, } x > 0\\text{)}$$\n\nDie **Stückkosten** (= Kosten pro Bauteil) sind:\n$$k(x) = \\frac{K(x)}{x} = 2x + 50 + \\frac{1800}{x}$$\n\n**Bei welcher Stückzahl $x$ sind die Stückkosten minimal?\nWie hoch sind die minimalen Stückkosten?**\n\nGeben Sie Ihr Ergebnis als `x; k_min` an.",
                answer: "30; 170",
                accepts: ["30; 170","30;170","x=30, k=170","30; 170 €"],
                hints: ["$k(x) = 2x + 50 + \\frac{1800}{x}$.\nAbleiten: $k'(x) = 2 - \\frac{1800}{x^2}$.","$k'(x) = 0$: $\\frac{1800}{x^2} = 2$ → $x^2 = 900$ → $x = 30$.\n$k''(x) = \\frac{3600}{x^3} > 0$ → Minimum.","$k(30) = 60 + 50 + 60 = 170\\,\\text{€/Stück}$."],
                errorPatterns: {"900; 170":"$x^2 = 900$, also $x = \\sqrt{900} = 30$, nicht $900$!","30; 110":"Haben Sie den Term $50$ vergessen? $k(30) = 2 \\cdot 30 + 50 + \\frac{1800}{30} = 60 + 50 + 60 = 170$.","30; 120":"Alle drei Terme addieren: $k(30) = 60 + 50 + 60 = 170$."}
            },
            {
                id: "ex8",
                question: "**Gewinnmaximierung bei einem Sensorhersteller**\n\nEin Unternehmen stellt Temperatursensoren für die Werkstoffprüfung her.\nDie **Preis-Absatz-Funktion** lautet:\n$$p(x) = 100 - 2x \\quad \\text{(€/Stück, } x \\text{ in Stück/Tag)}$$\n\nDie **Gesamtkosten** betragen:\n$$K(x) = x^2 + 10x + 200 \\quad \\text{(€/Tag)}$$\n\n**Bestimmen Sie die gewinnmaximale Stückzahl $x$, den zugehörigen\nVerkaufspreis $p$ und den maximalen Tagesgewinn $G_{\\max}$.**\n\nGeben Sie Ihr Ergebnis als `x; p; G_max` an.",
                answer: "15; 70; 475",
                accepts: ["15; 70; 475","15;70;475","x=15, p=70, G=475"],
                hints: ["Erlös: $E(x) = x \\cdot p(x) = 100x - 2x^2$.\nGewinn: $G(x) = E(x) - K(x) = 100x - 2x^2 - x^2 - 10x - 200 = -3x^2 + 90x - 200$.","$G'(x) = -6x + 90 = 0$ → $x = 15$.\n$G''(x) = -6 < 0$ → Maximum.","$p(15) = 100 - 30 = 70\\\\,\\\\text{€/Stück}$.\n$G(15) = -3 \\\\cdot 225 + 90 \\\\cdot 15 - 200 = -675 + 1350 - 200 = 475\\\\,\\\\text{€}$."],
                errorPatterns: {"15; 70; 675":"Das ist der Erlös, nicht der Gewinn! $G = E - K = 1050 - 200 - ... $ Rechnen Sie $G(15)$ nochmals.","15; 100; 475":"$p(15) = 100 - 2 \\cdot 15 = 70$, nicht $100$!","45; 70; 475":"$G'(x) = -6x + 90 = 0$ → $x = 15$, nicht $x = 45$."}
            },
            {
                id: "ex9",
                question: "**Modellkritik: Abkühlung eines Werkstücks**\n\nNach dem Härten wird ein Stahlwerkstück an Luft abgekühlt.\nFolgende Temperaturen werden gemessen:\n\n| $t$ (min) | 0 | 10 | 30 |\n|---|---|---|---|\n| $T$ (°C) | 90 | 50 | 24 |\n\nZwei Modelle werden angepasst:\n\n- **Modell A** (quadratisch): $T_A(t) = 0{,}09\\,t^2 - 4{,}9\\,t + 90$\n- **Modell B** (exponentiell): $T_B(t) = 20 + 70 \\cdot e^{-0{,}088\\,t}$\n\nBeide passen gut zu den Messdaten. Aber für $t = 50\\,\\text{min}$\nliefert Modell A den Wert $T_A(50) = 70\\,°\\text{C}$ — die Temperatur\nwürde also wieder **steigen**.\n\n**Welche Aussage ist korrekt?**",
                type: "choice",
                options: ["Modell A ist trotzdem besser, weil Polynome einfacher zu rechnen sind.","Modell B ist physikalisch sinnvoller, weil eine Abkühlung monoton verläuft — die Temperatur kann nicht von selbst wieder steigen.","Beide Modelle sind gleichwertig, da sie im Messbereich übereinstimmen.","Modell A ist besser, weil es den Wert $T = 70\\,°\\text{C}$ bei $t = 50$ korrekt vorhersagt."],
                correct: 1,
                hints: ["Physik: Ein heißes Werkstück an kühlerer Luft kühlt **monoton** ab —\ndie Temperatur nähert sich der Umgebungstemperatur und steigt nie wieder.","Das quadratische Modell hat ein Minimum bei $t \\approx 27$ min und steigt\ndanach wieder. Das widerspricht dem zweiten Hauptsatz der Thermodynamik.\nFür **Extrapolation** über den Messbereich hinaus ist das Exponentialmodell\nphysikalisch korrekt."],
            },
            {
                id: "ex10",
                question: "**Extrapolationsrisiko**\n\nDie Leistung $P$ (in kW) einer Photovoltaikanlage wird über einen Tag\ngemessen und durch ein Polynom vierten Grades modelliert:\n$$P(t) = -0{,}003\\,t^4 + 0{,}12\\,t^3 - 1{,}5\\,t^2 + 7\\,t$$\n($t$ in Stunden ab 6:00 Uhr, gültig für $0 \\leq t \\leq 14$)\n\nEin Praktikant berechnet $P(16)$ und erhält einen negativen Wert.\nEr folgert: „Die Anlage verbraucht abends Strom.\"\n\n**Erklären Sie in ein bis zwei Sätzen, warum die Aussage des\nPraktikanten falsch ist.**\n\nVerwenden Sie den Fachbegriff „Extrapolation\" in Ihrer Antwort.",
                answer: "Das Modell gilt nur im Bereich 0 ≤ t ≤ 14. Der Wert P(16) ist eine Extrapolation über den Gültigkeitsbereich hinaus und daher nicht aussagekräftig.",
                accepts: [".*[Ee]xtrapolation.*"],
                input_mode: "speech",
                hints: ["Was bedeutet „gültig für $0 \\leq t \\leq 14$\"?\nWas passiert, wenn man ein Modell außerhalb seines Gültigkeitsbereichs verwendet?","**Extrapolation** = Anwendung eines Modells außerhalb des Datenbereichs.\nPolynome können außerhalb ihres Gültigkeitsbereichs beliebig große oder\nkleine Werte annehmen — das hat keine physikalische Bedeutung."],
                errorPatterns: {}
            },
        ]
    },

};

const UNIT_ORDER = ["diagnose","steckbrief","modellierung","extremwert"];

// Gemini API (domain-restricted to hbraak.github.io)
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions';
const GEMINI_API_KEY = new URLSearchParams(window.location.search).get('key') || '';
const GITHUB_TOKEN = new URLSearchParams(window.location.search).get('ghtoken') || '';
const GIST_ID = '1adfc536c05ff59f6448fb95dcd3bb92';
const GEMINI_MODEL = 'gemini-2.5-flash';
